server:
  port: 8765


spring:
  application:
    name: APIGateWay
  cloud:
    gateway:
      routes:
        - id: MicroserviceOne
          uri: http://localhost:8081/
          predicates:
            - Path=/serviceOne/**
        - id: MicroserviceTwo
          uri: http://localhost:8082/
          predicates:
            - Path=/serviceTwo/**


